[server]
headless = true
enableCORS = false
enableXsrfProtection = true
port = 8501
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
base="dark"
primaryColor="#5AA9E6"
backgroundColor="#0B1220"
secondaryBackgroundColor="#111A2E"
textColor="#E6EAF2"
font="sans serif"